### PR TITLE
Fix for Get Element Attribute overloading

### PR DESCRIPTION
**Pull request by ractoc**
turns out it is not possible to work with overloaded methods when it comes to RF. So the old, 1 parameter, method had to be removed completely.

This also means a slightly different (uglier) way of getting the locator and attribute in there to keep everything backwards compatible.

The only way to get around using this uglier way is to break backwards compatibility though so this would seem the lesser of two evils for now.

### CODE REVIEW

**Comment by ractoc** [comment]
@Hi-Fi I kinda broke the thing with my last PR....
This should fix it.

Any idea when I can expect this fixed version?

**Comment by Hi-Fi** [comment]
There's separate annotation to overload methods within Java libraries. See e.g. `addLocationStrategy` at https://github.com/Hi-Fi/robotframework-seleniumlibrary-java/blob/develop/src/main/java/com/github/markusbernhardt/seleniumlibrary/keywords/BrowserManagement.java#L128

**Comment by ractoc** [comment]
Cool, I'll drop this change then in favor of adding that one...

**Comment by Hi-Fi** [comment]
It would be nice if you also can add test for both old and new way-

**Pull request closed without merging**
